### ISSUE TITLE
TypeError: Date.now is not a function when upgrading from 6.2.1 to 6.2.2 

### ISSUE THREAD

**Issue by dereklin** [ReactiveX/rxjs#4198]
I have some ngrx effect tests that work fine with rxjs 6.2.1.  After upgrading rxjs 6.2.2, I get this error:

I tried 6.3.3 as well.  I get the same problem.

```
   TypeError: Date.now is not a function                                                    
                                                                                                                            
      at Object.<anonymous>.Scheduler.now (node_modules/rxjs/src/internal/Scheduler.ts:31:48)                       
      at AsyncScheduler.now (node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:32:16)               
      at DelaySubscriber.Object.<anonymous>.DelaySubscriber.scheduleNotification (node_modules/rxjs/src/internal/operators/delay.ts:124:48)
      at DelaySubscriber.Object.<anonymous>.DelaySubscriber._next (node_modules/rxjs/src/internal/operators/delay.ts:133:10)
      at DelaySubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:102:12)        
      at MapSubscriber.Object.<anonymous>.MapSubscriber._next (node_modules/rxjs/src/internal/operators/map.ts:86:22)
      at MapSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:102:12)                                        
      at FilterSubscriber.Object.<anonymous>.FilterSubscriber._next (node_modules/rxjs/src/internal/operators/filter.ts:98:24)
      at FilterSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:102:12)  
      at ScannedActionsSubject.Object.<anonymous>.Subject.next (node_modules/rxjs/src/internal/Subject.ts:62:17)                  
      at SafeSubscriber._next (../../../../../execroot/ngrx/modules/store/src/state.ts:52:22)                                
      at SafeSubscriber.Object.<anonymous>.SafeSubscriber.__tryOrUnsub (node_modules/rxjs/src/internal/Subscriber.ts:270:10)
      at SafeSubscriber.Object.<anonymous>.SafeSubscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:212:14)              
      at Subscriber.Object.<anonymous>.Subscriber._next (node_modules/rxjs/src/internal/Subscriber.ts:142:22)               
      at Subscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:102:12)     
      at ScanSubscriber.Object.<anonymous>.ScanSubscriber._tryNext (node_modules/rxjs/src/internal/operators/scan.ts:116:22)         
      at ScanSubscriber.Object.<anonymous>.ScanSubscriber._next (node_modules/rxjs/src/internal/operators/scan.ts:103:19)                        
      at ScanSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:102:12)                       
      at WithLatestFromSubscriber.Object.<anonymous>.WithLatestFromSubscriber._next (node_modules/rxjs/src/internal/operators/withLatestFrom.ts:137:26)
      at WithLatestFromSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:102:12)
      at Notification.Object.<anonymous>.Notification.observe (node_modules/rxjs/src/internal/Notification.ts:36:42)     
      at QueueAction.Object.<anonymous>.ObserveOnSubscriber.dispatch (node_modules/rxjs/src/internal/operators/observeOn.ts:80:18)      
      at QueueAction.Object.<anonymous>.AsyncAction._execute (node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:121:12)
      at QueueAction.Object.<anonymous>.QueueAction.execute (node_modules/rxjs/src/internal/scheduler/QueueAction.ts:31:12)
      at QueueScheduler.Object.<anonymous>.AsyncScheduler.flush (node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:58:26)
      at QueueAction.Object.<anonymous>.QueueAction.schedule (node_modules/rxjs/src/internal/scheduler/QueueAction.ts:24:20)
      at QueueScheduler.Object.<anonymous>.Scheduler.schedule (node_modules/rxjs/src/internal/Scheduler.ts:66:52)
      at QueueScheduler.Object.<anonymous>.AsyncScheduler.schedule (node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:41:28)
      at ObserveOnSubscriber.Object.<anonymous>.ObserveOnSubscriber.scheduleMessage (node_modules/rxjs/src/internal/operators/observeOn.ts:91:29)
      at ObserveOnSubscriber.Object.<anonymous>.ObserveOnSubscriber._next (node_modules/rxjs/src/internal/operators/observeOn.ts:99:10)
      at ObserveOnSubscriber.Object.<anonymous>.Subscriber.next (node_modules/rxjs/src/internal/Subscriber.ts:102:12)
      at ActionsSubject.Object.<anonymous>.Subject.next (node_modules/rxjs/src/internal/Subject.ts:62:17)
      at ActionsSubject.Object.<anonymous>.BehaviorSubject.next (node_modules/rxjs/src/internal/BehaviorSubject.ts:40:15)
      at ActionsSubject.Object.<anonymous>.ActionsSubject.next (../../../../../execroot/ngrx/modules/store/src/actions_subject.ts:22:15)
      at Store.Object.<anonymous>.Store.dispatch (../../../../../execroot/ngrx/modules/store/src/store.ts:84:26)
      at apps/pretrade/src/app/core/store/effects/ticker.effects.spec.ts:300:13   
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at AsyncTestZoneSpec.Object.<anonymous>.AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:106:39)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:125:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.runGuarded (node_modules/zone.js/dist/zone.js:151:47)
      at runInTestZone (node_modules/zone.js/dist/async-test.js:234:29)
      at node_modules/zone.js/dist/async-test.js:168:17
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:388:26)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:128:39)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:387:32)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:138:43)
      at Object.testBody.length.done (node_modules/jest-zone-patch/index.js:51:29)
        
```

**Comment by cartant** [comment]
If your environment does not provide [`Date.now`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now), it will be up to you to polyfill it.

**Comment by dereklin** [comment]
@cartant Thanks!  It turns out we were overriding the Date in our test.  I had to add now back to the fake mockDate object.
