### ISSUE TITLE
filter predicate should have 'any' return type instead of 'boolean'

### ISSUE THREAD

**Issue by jbedard** [ReactiveX/rxjs#2741]
**RxJS version:**
5.4.2

**Code to reproduce:**
```javascript
Observable.of(1).filter(x => x)
```

**Expected behavior:**
Should compile.
The filter predicate should probably have a return type of `any` similar to the es5 array `filter` method.

**Actual behavior:**
Does not compile in TS 2.4 due to stricter type checking, and rxjs specificaly states that the filter predicate must return a `boolean`.

**Comment by kwonoj** [comment]
Dupe of https://github.com/ReactiveX/rxjs/issues/2173.

We had discussed this once, and for now two possible options is force type to truthy (`!!x`) or loosen type inferences to `any`, and so far we've decided to keep strict types and require truthy casting if needed. It doesn't mean it'll going to remain forever as-is, but at this moment we're planning to keep current behavior.

**Comment by jbedard** [comment]
In my case the filter predicate is imported so I don't have the option of doing `!!x` :(

`filter` is also [implemented using any](https://github.com/ReactiveX/rxjs/blob/5.4.2/src/operator/filter.ts#L88) which I thought was weird.

Also note that this changed in TS 2.4 causing compilation errors. In TS 2.3 my code worked just fine doing `.filter(importedFunc)` and now it is a TS compile error.

I thought being equivalent to es5 array `filter` would also be nice?

**Comment by david-driscoll** [comment]
in your case the easiest way would be to just cast the assignment to any `.filter(<any>importedFunc)`

**Comment by jbedard** [comment]
That's what I've done, I just thought this might be worth fixing since it changed with the recent TS v2.4.
