### ISSUE TITLE
error TS2557: Expected at least 0 arguments, but got 1 or more.

### ISSUE THREAD

**Issue by Medesko** [ReactiveX/rxjs#4279]
## Bug Report

**Current Behavior**
Hello, Please someone can help,
 after update to 6.3.3 I get in pipe TS2557: Expected at least 0 arguments, but got 1 or more.

**Reproduction**
- stackoverflow link:
https://stackoverflow.com/questions/52929467/after-update-to-6-3-3-i-get-in-pipe-error-ts2557-expected-at-least-0-argument

```js
return of(this.getRootHref()).pipe(
  ...pipeArguments,
  distinctUntilChanged()
);
```

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

**Environment**
- Runtime: [e.g. Node v 8.11.3]
- RxJS version: 6.3.3
- (If bug is related) Loader, build configuration: [e.g webpack, angular-cli version ~7.0.2, config]

**Comment by cartant** [comment]
https://github.com/ReactiveX/rxjs/issues/3989

**Comment by Medesko** [comment]
Hello @cartant,
I tried, but I can't adapt my code with your example,  here is my complete code.

```
  private getEndpointAt(...path: string[]): Observable<string> {
  if (!path) {
    path = ['/'];
  }
  console.log(path); // ["items", "search", "candidates"]
  let currentPath;
  const pipeArguments: any = path
    .map((subPath: string, index: number) => {
      return [
        flatMap((href: string) => {
          return this.getEndpointMapAt(href);
        }),
        map((endpointMap: EndpointMap) => {
          if (hasValue(endpointMap) && hasValue(endpointMap[subPath])) {
            currentPath = endpointMap[subPath];
            return endpointMap[subPath];
          } else {
            currentPath += '/' + subPath;
            return currentPath;
          }
        })
      ];
    })
    .reduce((combined, thisElement) => {
      return [...combined, ...thisElement];
    }, []);

  return of('http://localhost:8001/1/').pipe(
    ...pipeArguments,
    distinctUntilChanged()
  );
}
```

**Comment by jgbpercy** [comment]
Some more info in this issue https://github.com/ReactiveX/rxjs/issues/4177

Until the code linked to that issue is merged, I think you're stuck with the same `as any` hack seen [here](https://github.com/angular/angular-cli/pull/12357/files#diff-e2ed7d40edb832433e17c58f41ac6539), so:
```
return (of('http://localhost:8001/1/') as any).pipe(
    ...pipeArguments,
    distinctUntilChanged()
  );
```

The underlying implementation of pipe didn't change, but typing was fixed to remove an overload that was too loose. Unfortunately this broke the typing for spread args to pipe. But because the implementation is the same, spread args still work in 6.3.3 if you can convince TS that it's ok to pass them, which is of course as simple as type asserting `any`. Obviously that isn't ideal, especially if you have to do it in many places, but for 6.3 I think it's all you can do(?)
