### ISSUE TITLE
mergeMap/switchMap typing regression in v7

### ISSUE THREAD

**Issue by rraziel** [ReactiveX/rxjs#5698]
## Bug Report

**Current Behavior**
`mergeMap`, `switchMap`, etc. operators returns in an `Observable<unknown>`

**Reproduction**
```typescript
const other$ = of(42);
const res$ = of().pipe(
  switchMap(() => other$)
); // res$ is Observable<unknown>, was Observable<number> in rxjs 6
```

**Expected behavior**
Proper typing.

**Environment**
- Runtime: Node v12
- RxJS version: 7.0.0-beta.5
- TypeScript: 4.0 then downgraded to 3.9 in case it came from using the latest TS version

**Possible Solution**
n/a

**Additional context/Screenshots**
n/a

**Comment by cartant** [comment]
I've not been able to reproduce this with RxJS v6 or v7 or TS 3.9 or 4.0.

```ts
import { Observable, of } from "rxjs";
import { switchMap } from "rxjs/operators";

const other$ = of(42);
const res$ = of().pipe(switchMap(() => other$)); // inference shown in VSCode as Observable<number>
const number$: Observable<number> = res$; // no compiler error effected when running snippet
```

AFAICT, there have been no changes made to the typing of `switchMap` between [v6](https://github.com/ReactiveX/rxjs/blob/5c68e208512dd0f3ba1aafbf3e592592ec13db9b/src/internal/operators/switchMap.ts#L11-L15) and [v7](https://github.com/ReactiveX/rxjs/blob/cdffe79b986a89621342f2f16371d2338897c1dc/src/internal/operators/switchMap.ts#L12-L16).

If you are able to reproduce this in a minimal repo, I can have a look at it.

**Comment by cartant** [comment]
Never mind. It seems to be misbehaving in VSCode, now.

**Comment by cartant** [comment]
This does not appear to be an RxJS problem. VSCode works fine with RxJS v6 and v7 and with TS 4.0.2. Additionally, running the snippet - using `ts-node` and TS 4.0.2 - does not effect a compilation error (with any version combination, AFAICT) on the line:

`const number$: Observable<number> = res$;`.

I did see the inference of `Observable<unknown>` in VSCode, but I was unable to reproduce it after closing VSCode and running it **after** installing either RxJS v6 or v7 with TS 4.0.2. This - in addition to the types not having been changed - leads me to the conclusion that this is not a problem effected by the RxJS types.

**Comment by rraziel** [comment]
Ah my bad, I tried switching TS and RxJS versions - which seemed to work when going back to 6.x but that's probably because that's what I had in node_modules when VSCode started - but didn't think about restarting VSCode, sorry about that 😓 

But thanks a lot for taking the time to look into it!
