### ISSUE TITLE
Imports not resolving at all in some environments for RxJS 7.

### ISSUE THREAD

**Issue by benlesh** [ReactiveX/rxjs#6350]
### Issue: 

When trying to import _anything_ in RxJS 7, in some environments, in particular, stackblitz.com and codesandbox.io, the `"rxjs"` module does not seem to resolve. It worked fine with `rxjs@7.0.0-rc.2`, but not with `rxjs@7.0.0`. I suspect the references and the `typesVersions` addition are to blame.  What a mess.

It seems to work fine in most other "real world" environments, from my testing though.

[Broken codesandbox](https://codesandbox.io/s/frosty-merkle-yvqih?file=/src/index.ts)

[Broken stackblitz](https://rxjs-qnmamx.stackblitz.io)

![image](https://user-images.githubusercontent.com/1540597/116954291-32d5c480-ac55-11eb-839d-f0f5f3de29e1.png)

### Behavior:

Error message: `Cannot find module 'rxjs' or its corresponding type declarations.(2307)`

# Solution: rxjs@7 requires TypeScript 4.2 or higher please update TypeScript.

**Comment by cyrilletuzi** [comment]
For information, it happens in real world too: example [here](https://github.com/cyrilletuzi/angular-async-local-storage/pull/642/commits/8510401d21b068201f922f32c574d08b3f7adda0) (GitHub Actions checks of last commit of cyrilletuzi/angular-async-local-storage#642)

I linked to CI so you can see the issue directly, but same thing happen inside of VS Code.

**Comment by gritschf** [comment]
after updating to typescript `4.2.4` the problem would be gone. I say "would", because my angular project needs the typescript version to be < `4.2.0`

**Comment by benlesh** [comment]
@gritschf it's possible that codesandbox and stackblitz are still not TS 4.2. But I thought that stackblitz was, at least. 🤔
