### ISSUE TITLE
.pipe fn type overloads no longer support using spread arguments

### ISSUE THREAD

**Issue by rkirov** [ReactiveX/rxjs#3989]
## Bug Report

**Current Behavior**
After #3945, the following is now a type error:

```typescript
of(1, 2, 3).pipe(...[map((x) => x)]);

error TS2557: Expected at least 0 arguments, but got 0 or more.
```

Arguably, this is TS error as witnessed by the odd error msg.

**Possible Solution**
Not sure if it is possible to have the good behaviors #3945 introduced in terms of error reporting and passing spread args.

**Comment by rkirov** [comment]
cc @cartant

**Comment by cartant** [comment]
@rkirov I've been playing around with simple harness that uses overloads and rest parameters. With TypeScript 3.0, you can use tuple parameter extraction to make it work:

```ts
type Parameters<T> = T extends (...args: infer U) => any ? U : never;

function f<A>(): {};
function f<A>(a: A): {};
function f<A>(a: A, ...rest: any[]): {};
function f(...rest: any[]): {} {
  return {};
}

const pf: Parameters<typeof f> = [1, 2, 3];
const rf = f(...pf); // OK
```

Note that the `pf` variable that's spread needs to have the appropriate tuple type. Otherwise, the error you mentioned is effected:

```ts
const pf = [1, 2, 3];
const rf = f(...pf); // error TS2557: Expected at least 0 arguments, but got 0 or more.
```

Because the inclusion of a signature with a single rest parameter matches operators with types that would otherwise be deemed incompatible, I don't think one can be reinstated.

Perhaps exposing the [`pipeFromArray`](https://github.com/ReactiveX/rxjs/blob/6.2.2/src/internal/util/pipe.ts#L21-L34) function would be a suitable workaround?

**Comment by cartant** [comment]
It's also worth noting that spreading would have only worked in 6.2.1 and 6.2.2 - after #3789 was merged. And the change in that PR circumvented the type checking performed by the other signatures.

In releases prior to that - [including v5](https://github.com/ReactiveX/rxjs/blob/5.5.11/src/Observable.ts#L302) - the catch-all signature was typed in such away that spreading would not have worked in many circumstances:

```ts
pipe<R>(...operations: OperatorFunction<T, R>[]): Observable<R>
```

**Comment by MatissJanis** [comment]
Anyone knows a workaround to this issue?

**Comment by cartant** [comment]
@MatissJanis See the two comments immediately above yours.

**Comment by MatissJanis** [comment]
Sadly I can't use Typescript v3, but only v2. Do you know any solution for an older Typescript version?

**Comment by cartant** [comment]
@MatissJanis Unfortunately, the `pipeFromArray` utility is internal. It's what you really need. Without it you could cook up your own or use `reduce`, like this:

```ts
const ops = [map((x) => x)];
const result = ops.reduce((ob: Observable<{}>, op: OperatorFunction<{}, {}>) => ob.pipe(op), of(1, 2, 3));
result.subscribe(value => console.log(value));
```

It ain't pretty, but you could wrap that in a function to impose a particular result type, etc.

**Comment by MatissJanis** [comment]
Got it. Thanks for the fast replies @cartant!

**Comment by gromovich** [comment]
Ot dushi, @cartant!

**Comment by Medesko** [comment]
Hello, 

Please can someone help me, after update to Rxjs 6.3.3 I got this error TS2557: Expected at least 0 arguments, but got 1 or more.

`  const pipeArguments = path
      .map((subPath: string, index: number) => {
        return [
          flatMap((href: string) => {
            return this.getEndpointMapAt(href);
          }),
          map((endpointMap: EndpointMap) => {
            if (hasValue(endpointMap) && hasValue(endpointMap[subPath])) {
              currentPath = endpointMap[subPath];
              return endpointMap[subPath];
            } else {
              /*TODO remove if/else block once the rest response contains _links for facets*/
              currentPath += '/' + subPath;
              return currentPath;
            }
          })
        ];
      })
      .reduce((combined, thisElement) => [...combined, ...thisElement], []);
    **return of(this.getRootHref()).pipe(
      ...pipeArguments,
      distinctUntilChanged()**
    );`

**Comment by tanou73** [comment]
+1
Faced the issue as well while upgrading to ng7 (thus moving to typescript 3).
Thanks to @cartant, the  _pipeFromArray_ workaround worked great for me.
In case there are anyone in the same situation, here is a simplified snippet of the workaround (because code speak better than words 😃 ):

```
// Before
req.pipe(...operators);

// After
pipeFromArray([...operators])(req);
```

**Comment by h4t0n** [comment]
+1 

I'm using _pipeFromArray_. It works

This is my code. I'm using a common response handler for http call.
`
       pipeFromArray(EntityManagerService.commonHandler)(this.http.get( ___ params___ ));

 private static commonHandler: OperatorFunction<any, any>[]  =
        [retry(3), catchError(EntityManagerService.handleError)];

`

**Comment by afmeva** [comment]
you could also use the apply function:

before:
```.pipe(...selectors)```

after: 
```.pipe.apply(context, selectors)```
