### ISSUE TITLE
Subject<void> and next() optional value - (Typescript checks)

### ISSUE THREAD

**Issue by sorduz98** [ReactiveX/rxjs#6499]
## Bug Report

**Current Behavior**
 I am using "tokenRefreshedSource" subject only as a signal, without any arguments.

`private tokenRefreshedSource = new Subject<void>();`

With the last version of RxJs (7.1.0). This gives typescript error: 

```
error TS2554: Expected 1 arguments, but got 0.
[ng] 212           this.tokenRefreshedSource.next();
```

**Expected behavior**
It should allow to call next without any arguments on 'void'.

**Environment**
- Runtime: Chrome
- Node: 14.7.1
- RxJS version: 7.1.0
- Angular-cli: 12.1.0
- Ionic-cli: 6.12.3

**Possible Solution**
Allow to pass no arguments.

**Additional information**
It seems to be a previous bug: https://github.com/ReactiveX/rxjs/issues/1728

**Comment by kwonoj** [comment]
Please provide reproducible repo, this is the case we have test cases https://github.com/ReactiveX/rxjs/blob/master/spec-dtslint/Subject-spec.ts#L23-L31 passing for master / 7 both.

**Comment by martinsik** [comment]
@sorduz98 Seems to be working in 7.1.0 https://stackblitz.com/edit/rxjs-p4m3jf?devtoolsheight=60
Maybe post your TypeScript version as well.

**Comment by sorduz98** [comment]
I'm not sure why but I haven't been able to reproduce this behavior again, I'm sorry :(.
