### PR TITLE
Add concatMap overload to include changes from Google

### PR DESCRIPTION
**Pull request by kolodny**
This PR includes downstream changes in Google that were needed to keep the build green for a vast amount of projects when updating to v7-alpha

### CODE REVIEW

**Comment by kolodny** [comment]
Done

**Comment by cartant** [comment]
A similar signature should be added to the other flattening operators, too, IMO. I'll open a PR later.

**Comment by kolodny** [comment]
@cartant You're right, the test I gave was a poor one. I created a test which more closely matches what exactly is breaking internally and why this change was needed. Note that this is only breaking in one place (albeit a whole bunch of targets rely on this breaking helper function) so I can fix it in this internally and there wouldn't be a need for the PR, but it does seem that this PR is introducing better types overall

File: spec-dtslint/operators/concatMap-spec.ts [hunk 1]
```diff
@@ -33,6 +33,10 @@ it('should support union-type projections', () => {
   const o = of(Math.random()).pipe(concatMap(n => n > 0.5 ? of('life') : of(42))); // $ExpectType Observable<string | number>
 });
 
+it('should support union-type projections with empty streams', () => {
+  const o: Observable<number> = of(1, 2, 3).pipe(concatMap(n => Math.random() < 0.5 ? of(123) : of()));
```
Comment (cartant) [inline spec-dtslint/operators/concatMap-spec.ts]: This needs to be written as:

```ts
const o = of(1, 2, 3).pipe(concatMap(n => Math.random() < 0.5 ? of(123) : of())); // $ExpectType Observable<number>
```

dtslint doesn't care about or report compilation errors. An expectation is required, otherwise dtslint would pass this even if the inferred return type wasn't assignable to `Observable<number>`.

**Comment by cartant** [comment]
I don't think we can make the change in this PR. Not to `concatMap` nor to any of the other flattening operators.

In #4983, I made the change to the other flattening operators and it broke a test - see the log in that PR. For whatever reason, the `mergeMap` operator in the

```ts
it('should not break unsubscription chains when unsubscribed explicitly', () => {
```

in `combineAll-spec.ts` infers matches the signature and infers `Observable<never>`. Why this is the case, IDK, but we cannot make this change without breaking people's code, IMO.

**Comment by kolodny** [comment]
I'm not 100% clear on why that tests would start failing with changing `combineAll` TBH. Do note that this PR is not needed for our use case once https://github.com/ReactiveX/rxjs/pull/4976 lands since that ensures `of()` emits a `never` and `never`s disappear in unions. I'd recommend just waiting for that PR to land and close this as obsolete once that happens.

**Comment by cartant** [comment]
IDK either. Specifically, it fails because the `mergeMap` on [this line](https://github.com/ReactiveX/rxjs/blob/b0fe2866989bff76431304ee71a8299d4cc341a6/spec/operators/combineAll-spec.ts#L174) infers `Observable<never>`. You should be able to switch that out - temporarily - with `concatMap` in your own PR to see the compilation failure.

The observables in that are merged/concatenated in that test are higher-order observables, but that should make no difference. It's entirely possible that this is a TypeScript bug, but if we cannot determine why the signature is matched - and the a compilation error is effected for valid code - I don't see how we can merge this change.

**Comment by kolodny** [comment]
This PR isn't needed anymore and in fact will break the build if it's included. closing this PR
