### ISSUE TITLE
Subscription to Observable is not removed from observers array after unsubscribe()

### ISSUE THREAD

**Issue by ababashka** [ReactiveX/rxjs#4230]
## Bug Report

**Current Behavior**
Currently subscription isn't removed from **observers** array after unsubscribe, both with takeUntil() and unsubscribe().

**Reproduction**

```js
function called() { console.log('CALLED'); }

const subject = new Subject();
const destroyed = new Subject();

const subscription = subject
        .pipe(takeUntil(destroyed))
        .subscribe(() => called());

console.log(subject.observers.length); // 1

subject.next(); // CALLED
subject.next(); // CALLED

// Unsubscribe from subject
destroyed.next(true);
destroyed.complete();

console.log(subject.observers.length); // Still 1, expected: 0

subscription.unsubscribe();
subject.next(); // no console.log('CALLED')

console.log(subject.observers.length); // Still 1, expected: 0
```

**Expected behavior**
In 2 last **console.log(subject.observers.length)** it's expected to have **0** : observer should be removed from array of **observers** after **unsubscribe()**

**Environment**
- RxJS version:
- 6.3.3

**Additional notes**
It isn't reproducible with **rxjs** version 6.2.2

**Comment by mdepasquale21** [comment]
same issue here after upgrading from 6.3.2 to 6.3.3

**Comment by cartant** [comment]
For me, this issue's repro outputs the expected counts:

```
$ ts-node index.ts
1
CALLED
CALLED
0
0
```

The code is unchanged:

```ts
import { Subject } from "rxjs";
import { takeUntil } from "rxjs/operators";

function called() { console.log('CALLED'); }

const subject = new Subject();
const destroyed = new Subject();

const subscription = subject
  .pipe(takeUntil(destroyed))
  .subscribe(() => called());

console.log(subject.observers.length); // 1

subject.next(); // CALLED
subject.next(); // CALLED

// Unsubscribe from subject
destroyed.next(true);
destroyed.complete();

console.log(subject.observers.length); // Still 1, expected: 0

subscription.unsubscribe();
subject.next(); // no console.log('CALLED')

console.log(subject.observers.length); // Still 1, expected: 0
```

**Comment by ababashka** [comment]
@cartant You are right, i've started new (angular) project and couldn't reproduce this issue with RxJS 6.3.3.
But still i can reproduce it here:
https://stackblitz.com/edit/rxjs-me3evv?file=index.ts

I've copied content of **node_modules/rxjs/bundles/rxjs.umd.js** bundle and put it into file **rxjsbundle.js** in my example on **stackblitz**.

Also, some additional note: i found this issue in my angular project's test and when i start this karma test with ng - it's reproducible. I've updated only **rxjs** in my **package.json** (from **6.2.2** to **6.3.3** as i mentioned previously) - and that failed.

Thanks for your time and would be nice if you could clarify this.

**Comment by cartant** [comment]
So are you saying that it's only reproducible when using the bundle that's in 6.3.3?

**Comment by ababashka** [comment]
Actually i've just tried to copy bundle's content to my example from versions **6.3.2**, **6.3.1** and even from **6.2.2** - it's still reproducible with stackblitz and that's pretty strange.
But the test got failed only with **RxJS** version **6.3.3** and is working with **6.3.2**

**Comment by cartant** [comment]
This works fine for me, too:

```html
<html>
<body>
<script src="./node_modules/rxjs/bundles/rxjs.umd.js"></script>
<script>

const { Subject } = rxjs;
const { takeUntil } = rxjs.operators;

function called() { console.log('CALLED'); }

const subject = new Subject();
const destroyed = new Subject();

const subscription = subject
    .pipe(takeUntil(destroyed))
    .subscribe(() => called());

console.log(subject.observers.length); // 1

subject.next(); // CALLED
subject.next(); // CALLED

// Unsubscribe from subject
destroyed.next(true);
destroyed.complete();

console.log(subject.observers.length); // Still 1

subscription.unsubscribe();
subject.next(); // no console.log('CALLED')

console.log(subject.observers.length); // Still 1

</script>
</body>
</html>
```

**Comment by mdepasquale21** [comment]
In my case I have a working angular app (cli version 6.2.4, with rxjs 6.3.2) , in which I have a component behaving more or less like this:

```
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Subscription } from 'rxjs';
import { tap } from 'rxjs/internal/operators';

export class MyComponent implements OnInit, OnDestroy {
    myObservable: Observable<T>;
    mySubscription: Subscription;

    ngOnInit() {
        console.log('subscription');
        this.mySubscription = this.myObservable.pipe(
            tap(() => {
                console.log('do stuff with observable');
            })
        ).subscribe(
            () => {
                console.log('do other stuff!');
            }
        );
    }

    ngOnDestroy() {
        console.log('unsubscribe');
        this.mySubscription.unsubscribe();
     }
}
```

After the update to rxjs 6.3.3, in the console I see:
    > subscription
    > do stuff with observable
    > do other stuff!
    > unsubscribe
    > stuff with observable

**Comment by cartant** [comment]
@mdepasquale21 For this problem to manifest, I think you'd need to have multiple copies of RxJS installed in `node_modules` - either different versions or the same version in different locations.

Run `npm list rxjs` in your project's root to see what's installed.

**Comment by lowe0292** [comment]
Pretty sure this defect resulted in a huge memory leak across a bunch of our angular sites. 

Reverting to rxjs 6.2.2 resolved the issue for us.

**Comment by danielgeri** [comment]
hi all - i am still a bit confused as to why there would be different version of rxjs installed for an angular application, especially when rxjs is listed as a peerDependency. I did a build w/o optimzation to check to see if there were multiple versions of rxjs installed and couldn't find more than 1. Also, when i run `npm list rxjs`, the version returned is 6.2.2; however when i look inside ./node_modules, I can clearly see that 6.3.3 is installed. I guess I would expect `npm list rxjs` to return 6.3.3? Admittedly, this is more of a `how does npm work` question rather than a rxjs question, but hoping someone here could enlighten me since it's related :). Thanks all!

**Comment by Spawnrad** [comment]
Same isssue here since i have update from 6.3.2 to 6.3.3

**Comment by mdepasquale21** [comment]
@danielgeri I'm not sure either, the only thing I can suggest is that you try to delete node_modules directory and run `npm install` to reinstall everything from scratch. In my case when I tried this solution it didn't work. I had rxjs listed as a peer dependency but other libraries in my package.json which depend on rxjs for some reason were using a different version. For me it was completely unexpected, I had to revert to rxjs 6.2.2. Anyway after updating to Angular 7 everything works fine and I could finally use rxjs 6.3.3.

**Comment by Spawnrad** [comment]
I tried everything with deleting node_modules directory.

Angular 6 and rxjs 6.3.3  => not working
Angular 6 and rxjs 6.32 => working

Angular 7 and rxjs 6.3.3 => not working
Angular 7 and rxjs 6.3.2 => working

**Comment by jnizet** [comment]
FWIW, I've had the same issue when upgrading from 6.3.2 to 6.3.3, and the bug was in fact caused by an incorrect import: I imported from 'rxjs/internal/operators' instead of 'rxjs/operators'.

**Comment by cartant** [comment]
@jnizet Do you have a minimal reproduction? I have an idea of how using the internal import location could be problematic, but I'd like to reproduce the problem. Mostly because I'm curious.

**Comment by jnizet** [comment]
I don't have a public one. I'll try creating one if I have some time, but it won't be now.

**Comment by mdepasquale21** [comment]
May be related with the discussion, I have an update with respect to my previous answer and in light of @jnizet 's answer: with angular 7 and rxjs 6.3.3 I thought everything was working fine, but instead I had a huge, random bug on initialization of the app! Sometimes the app just did not start, loading forever while sometimes started normally with no errors. So this 'init' bug appeared randomly without apparent reason whatsoever and it was difficult to reproduce and therefore to solve. I noticed I had several imports from 'rxjs/internal/operators' and changed them to import from 'rxjs/operators' as @jnizet suggested. This solved the problem finally (or at least it looks like, the bug has never appeared again since then).

**Comment by tiagowanke** [comment]
I have the same issue.
I downgraded to rxjs 6.3.2 and now is working.

**Comment by Spawnrad** [comment]
it looks like it work well with the new version 6.4.0. If someone can confirm ;)

**Comment by BenjaminBuick** [comment]
This issue is related to the `pipe()` operator - removing the operator before `subscribe()` restores functionality of the **Subscription's** object `unsubscribe` method. 

I had this issue in combination with Angular 7. Using different versions (6.3.3 or 6.4.0 ...) had no effect. Angular versions are predeterming the rxjs version anyway.

**Comment by cartant** [comment]
@BenjaminBuick If you have one, a reproduction of the problem would be appreciated. The comment you have left is unclear and not actionable, IMO.

**Comment by marianolop22** [comment]
Hi, same problem here
Angular CLI: 7.2.4
npm list rxjs
adminpro@0.0.0 C:\Desarrollo\Angular2\adminPro
+-- @angular-devkit/build-angular@0.12.4
| +-- @angular-devkit/architect@0.12.4
| | `-- rxjs@6.3.3  deduped
| +-- @angular-devkit/build-webpack@0.12.4
| | `-- rxjs@6.3.3  deduped
| +-- @angular-devkit/core@7.2.4
| | `-- rxjs@6.3.3  deduped
| +-- @ngtools/webpack@7.2.4
| | `-- rxjs@6.3.3  deduped
| `-- rxjs@6.3.3  deduped
+-- @angular/cli@7.2.4
| +-- @angular-devkit/schematics@7.2.4
| | `-- rxjs@6.3.3  deduped
| +-- @schematics/update@0.12.4
| | `-- rxjs@6.3.3  deduped
| `-- inquirer@6.2.1
|   `-- rxjs@6.3.3  deduped
`-- rxjs@6.3.3

the code:

  subscription: Subscription;

  constructor() {
    this.subscription = this.contarTresInfinito().subscribe(
      (response: any) => {
        console.log('respuesta', response);
      },
      (error) => {
        console.error('hay error', error);
  
      }).add(
        () => {
          console.log('terminó')
      });
  }

  ngOnDestroy() {
    this.subscription.unsubscribe();
    console.log ('la pagina se va a cerrar');
  }

  public contarTresInfinito(): Observable<any> {

    return new Observable((observer: Subscriber<any>) => {

      let contador = 0;
      let intervalo = setInterval(() => {

        contador++;

        const salida = {
          valor: contador
        }

        observer.next(salida); //esto es lo que notifica

      }, 1000);

    }).pipe(
      map(response => {
        return response.valor;
      }),
      filter((response, index) => { //el filter siempre devuelve un bool, el primer valor es el response y el segundo la cantidad de veces que es llamado

        if ((response % 2) == 1) {
          //impar
          return true;
        } else {
          //par
          return false;
        }
      })
    );

it never unsubscribe.

**Comment by marianolop22** [comment]
well, i update the rxjs to 6.4.0, and then removed this line of the code
.add(
    () => {
      console.log('terminó')
  });

now works perfect.

**Comment by hadirsa** [comment]
I use` angular 7.2.0` and `rxjs 6.3.3` My problem is like this below. `unsubscribe()` has no effect and `this.subscription.unsubscribe()` in `ngOnDestroy(){}`.
is this problem persists?

**Comment by marianolop22** [comment]
> I use` angular 7.2.0` and `rxjs 6.3.3` My problem is like this below. `unsubscribe()` has no effect and `this.subscription.unsubscribe()` in `ngOnDestroy(){}`.
> is this problem persists?

do you have this line? .add() at the end of your subscribe?

**Comment by valentinabojan** [comment]
We faced the same issue with rxjs 6.3.3. After reading through all the comments here, we discovered that there was indeed a bad import of switchMap from rxjs/internal/operators. After fixing this import, everything works as expected.

**Comment by cartant** [comment]
With the absence of minimal reproduction - and with reports that the problem is due to importing an internal file - IMO, this issue should just be closed.

**Comment by PaulAGH** [comment]
I also started encountering this after upgrading from Angular 6 to 7.  On Chrome everything would behave, but on Firefox I would observe the following as the app would initialize.

> Unhandled Promise rejection: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable. ; Zone: <root> ; Task: Promise.then ; Value: TypeError: "You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable."

I tried different versions of rxjs, examining closely npm list, etc - all to no avail.

Finally what did the trick was to change 
import {Subject} from 'rxjs/index';        //This did not cause issues before the upgrade
to
import {Subject} from 'rxjs';

Crazy stuff!

**Comment by ztnark** [comment]
@PaulAGH I agree. This almost drove me mad :)

>It seems like import statements from 'rxjs/index' and 'rxjs/internal/*' (and perhaps others) should cause compilation errors.

**Comment by cartant** [comment]
I've added an `rxjs-no-index` rule to https://github.com/cartant/rxjs-tslint-rules/ and a `no-index` rule to https://github.com/cartant/eslint-plugin-rxjs. I would recommend using one of those rules to guard against explicit importation from an index module.

**Comment by char-m** [comment]
Why this should be closed? Isn't this a major issue which can lead to hard to find defects when you don't assume that code is run after unsubscribe? I don't have any imports from 'rxjs/index' or 'rxjs/internal/* and i still experience this. I have also uninstalled rxjs and installed 6.3.2 and it still doesn't work as expected.

**Comment by char-m** [comment]
I tried to create stackblitz but it's not reproducible there.

**Comment by char-m** [comment]
> I've made numerous requests for a minimal reproduction and - unless I've missed something - none has been provided. So this is not actionable, IMO.
> 
> It's possibly related to what #5059 will fix, but without a repro ... 🤷‍♂

I questioned closing the issue on false premise. Sorry about confusion.

**Comment by JanEggers** [comment]
Im having the same issue. looking at the code I wonder why 

https://github.com/ReactiveX/rxjs/blob/06f1a25123997e0419a421aa949e8969bc5daeb1/src/internal/Subscriber.ts#L130-L136

does not this.destination.unsubscribe()

**Comment by cartant** [comment]
As I've said above:

> I've made numerous requests for a minimal reproduction and - unless I've missed something - none has been provided. So this is not actionable, IMO.

Seriously, no one is going to be able to answer any questions about this without a minimal reproduction of the problem.

**Comment by danger89** [comment]
Any news?

**Comment by cartant** [comment]
Closing this because it cannot be reproduced.
