### ISSUE TITLE
Can't import rxjs 6 from ts-node - types not found

### ISSUE THREAD

**Issue by ekasprzyk** [ReactiveX/rxjs#6477]
**RxJS version:**

6

**Code to reproduce:**

```
import yargs from "yargs";
import { Subject } from 'rxjs';
import { switchMap, map, tap } from 'rxjs/operators';
import contentfulEnvironment, { DEFAULT_LOCALE } from "../../src/contentful";
import { Entry } from "contentful-management/dist/typings/entities/entry";

const changeId = async (sourceId: string, destinationId: string) => {
  const input = new Subject<string>();
  const output = new Subject<string>();

  const client = await contentfulEnvironment();

  // const pipeline = combineLatest([
  //   contentfulEnvironment(),
  //   input,
  // ]);

  const pipeline = input;

  pipeline.pipe(
    switchMap((source: string) => {
      return client.getEntry(source);
    }),
    tap((sourceEntry: Entry) => {console.log(JSON.stringify(sourceEntry, null, 2))}),
    switchMap((sourceEntry: Entry) => {
      return client.createEntryWithId(sourceEntry.sys.contentType.sys.id, destinationId, {
        fields: sourceEntry.fields,
      });
    }),
    tap((createdEntry: Entry) => {console.log(JSON.stringify(createdEntry, null, 2))}),
    map((createdEntry: Entry) => createdEntry.sys.id),
  )

  pipeline.subscribe((createdEntryId: string) => {
    output.next(createdEntryId);
    output.complete();
  });

  output.subscribe((value: string) => {
    console.log(value);
  });
  input.next(sourceId);
  return output.toPromise();
};

const options = yargs(process.argv)
  .option("source", {
    alias: "s",
    demandOption: true,
    type: "string",
    description: "The id of the source data",
  })
  .option("destination", {
    alias: "d",
    demandOption: true,
    type: "string",
    description: "The desitnation id we're moving the data to"
  })
.argv;

(async () => {await changeId(options.source, options.destination)})();
```

**Expected behavior:**

Executing the above should work with ts-node (v9.0.0)

All documentation indicates the types are bundled with the package, but the types are not found.

**Actual behavior:**

```

scripts/general/change-id.ts:2:25 - error TS7016: Could not find a declaration file for module 'rxjs'. '/Users/ela/Projects/dtplus-new/contentful-shell-scripts/node_modules/rxjs/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/rxjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'rxjs';`

2 import { Subject } from 'rxjs';

```

**Additional information:**

Same problem with explicit tsroots aimed at node modules.  Other packages with implicit types are detected fine.

**Comment by cartant** [comment]
Works fine for me with RxJS v6 and either ts-node 9 or 10.

**Comment by cooperate** [comment]
Same problem.

**Comment by cartant** [comment]
Closing this because there is no minimal reproduction and I cannot reproduce the problem. Be aware that there is a minimum TypeScript version of 4.2 for version 7 - sure, version 6 is mentioned in the description, but there is no reproduction - and that the problem effected with pre-version-4.2 versions of TypeScript is the problem that's described in this issue. See https://github.com/ReactiveX/rxjs/issues/6350
