### ISSUE TITLE
Support building with typescript 2.5.2

### ISSUE THREAD

**Issue by pravi** [ReactiveX/rxjs#2884]
We'd like to build rxjs with typescript 2.5.2 in debian, but build fails with some errors

**RxJS version:**

5.4.3

**Code to reproduce:**

rxjs code

**Expected behavior:**

Should build with typescript 2.5.2

**Actual behavior:**

Gives errors during compilation
```
tsc ./dist/cjs/src/Rx.ts ./dist/cjs/src/add/observable/of.ts -m commonjs --lib es5,es2015.iterable,es2015.collection,es2015.promise,dom --sourceMap --outDir ./dist/cjs --target ES5 -d --diagnostics --pretty --noImplicitAny --noImplicitReturns --noImplicitThis --suppressImplicitAnyIndexErrors --moduleResolution node

57   static create<T>(target: EventTargetLike, eventName: string, selector: SelectorMethodSignature<T>): Observable<T>;
            ~~~~~~

dist/cjs/src/observable/FromEventObservable.ts(57,10): error TS2394: Overload signature is not compatible with function implementation.


182         (<GenerateOptions<T, S>>initialStateOrOptions).resultSelector || selfSelector,
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

dist/cjs/src/observable/GenerateObservable.ts(182,9): error TS2345: Argument of type '(<T>(value: T) => T) | ResultFunc<S, T>' is not assignable to parameter of type 'ResultFunc<S, T>'.
  Type '<T>(value: T) => T' is not assignable to type 'ResultFunc<S, T>'.
    Type 'S' is not assignable to type 'T'.


191         selfSelector,
            ~~~~~~~~~~~~

dist/cjs/src/observable/GenerateObservable.ts(191,9): error TS2345: Argument of type '<T>(value: T) => T' is not assignable to parameter of type 'ResultFunc<S, T>'.


250         xhr.responseType = request.responseType;
            ~~~~~~~~~~~~~~~~

dist/cjs/src/observable/dom/AjaxObservable.ts(250,9): error TS2322: Type 'string' is not assignable to type 'XMLHttpRequestResponseType'.

Files:           356
Lines:         39575
Nodes:        172478
Identifiers:   56005
Symbols:      107512
Types:         22496
Memory used: 160456K
I/O read:      0.04s
I/O write:     0.12s
Parse time:    0.82s
Bind time:     0.33s
Check time:    2.23s
Emit time:     1.35s
Total time:    4.73s
```
**Additional information:**

**Comment by kwonoj** [comment]
This should be fixed via https://github.com/ReactiveX/rxjs/pull/2896.
