### ISSUE TITLE
Probable regression in ajax.getJSON after updating to 5.0.0-beta.11

### ISSUE THREAD

**Issue by zavan** [ReactiveX/rxjs#1874]
**RxJS version:**
5.0.0-beta.11

**Code to reproduce:**
```javascript
import { Observable } from 'rxjs/Observable';
import { ajax } from 'rxjs/observable/dom/ajax';

console.log(ajax.getJSON('/api/v2/users'));
```

**Expected behavior:**
`AjaxObservable { _isScalar: false, request: Object }`

**Actual behavior:**
`Uncaught (in promise) TypeError: (intermediate value).map is not a function(… ) in ajaxGetJSON`

**Additional information:**
This is probably a regression caused by this commit: https://github.com/ReactiveX/rxjs/commit/7a77437205a18905b0c2974fedf0ee4e8c624bd6 
Introduced in 5.0.0-beta.11, since it works fine if I downgrade to 5.0.0-beta.10.

I'm using rxjs with redux-observable, if that makes any difference.

**Comment by kwonoj** [comment]
It seems it's due to https://github.com/ReactiveX/rxjs/commit/7a77437205a18905b0c2974fedf0ee4e8c624bd6#diff-f80ecdc9803b338b8f47819f25b3a721R89, `ajax` now depends on `map`, while your reproducible import does not imports map operator patches to observable. 

I'll try to update implementation, meanwhile import `add/../map` will resolve issue as immediate workaround.

**Comment by kwonoj** [comment]
@zavan , changes are checked in in master. You can verify behavior using master, or either wait next release published. Thanks for catching out issue!

**Comment by zavan** [comment]
@kwonoj Cool! Thank you for fixing it.
