### ISSUE TITLE
Types of property 'schedule' are incompatible after upgrading to 6.5.1

### ISSUE THREAD

**Issue by markgoho** [ReactiveX/rxjs#4746]
## Bug Report

**Current Behavior**
After upgrading to Angular 7.2.14 which also upgrades to Rxjs 6.5.1 I get an error when trying to serve any of the appins my project:
``` bash
ERROR in node_modules/rxjs/src/internal/scheduled/scheduled.ts(25,40): error TS2345: Argument of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("C:/Users/markg/Documents/GitHub/ui-
suite/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/types").SchedulerAction<T>' is not assignable to type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/types").SchedulerAction<T>'.
            Types of property 'schedule' are incompatible.
              Type '(state?: T, delay?: number) => import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type '(state?: T, delay?: number) => import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/Subscription").Subscription'.
                Type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/Subscription").Subscription'.
                  Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(27,37): error TS2345: Argument of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(29,35): error TS2345: Argument of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(31,38): error TS2345: Argument of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/observable/from.ts(116,29): error TS2345: Argument of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/types").SchedulerLike' is not assignable to parameter of type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("C:/Users/markg/Documents/Gi
tHub/ui-suite/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/types").SchedulerAction<T>' is not assignable to type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/types").SchedulerAction<T>'.
            Types of property 'schedule' are incompatible.
              Type '(state?: T, delay?: number) => import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type '(state?: T, delay?: number) => import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/Subscription").Subscription'.
                Type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type 'import("C:/Users/markg/Documents/GitHub/ui-suite/node_modules/rxjs/internal/Subscription").Subscription'.
                  Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.
```

**Environment**
- Runtime: node 10.12.0
- RxJS version: 6.5.1

**Comment by benlesh** [comment]
Do you have a reproduction repository we can look at?

**Comment by cartant** [comment]
I'm curious to know why there is an import that references `node_modules/rxjs/src/internal/scheduled/scheduled.ts`. Nothing should be imported from the `src` directory, IIRC. Could you have some rogue, IDE-generated/guessed import path someplace? What happens if you delete said directory? Where is that particular import being made?

**Comment by markgoho** [comment]
@cartant I deleted the folder and _immediately_ saw the issue!

Someone had this in a file:
`import { OperatorFunction } from 'rxjs/src/internal/types';`

I removed it and issue resolved! Yay!

**Comment by adhivenkatesh** [comment]
Hi any one to solve this issue.


ERROR in node_modules/rxjs/src/internal/scheduled/scheduled.ts(25,40): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of
type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?:
T) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerAction<T>' is
not assignable to type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerAction<T>'.
            Types of property 'schedule' are incompatible.
              Type '(state?: T, delay?: number) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type '(state?: T, delay?: number) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription'.
                Type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription'.
                  Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(27,37): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(29,35): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(31,38): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/observable/from.ts(116,29): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerAction<T>' is not assignable to type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerAction<T>'.
            Types of property 'schedule' are incompatible.
              Type '(state?: T, delay?: number) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type '(state?: T, delay?: number) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription'.
                Type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription'.
                  Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.

**Comment by MDzyga** [comment]
Check if you have 'rxjs/src in some imports
