### ISSUE TITLE
Typings for pipable operators get confused.

### ISSUE THREAD

**Issue by krodyrobi** [ReactiveX/rxjs#3486]
```
"dependencies": {
    "rxjs": "6.0.0-beta.3",
    "typescript": "2.8.1",
    "typings": "2.1.1"
  }
```
Also happens with typescript `2.7.2`

**Code to reproduce:**

```typescript
import {Observable, from} from 'rxjs';
import {take, concatAll, skip} from 'rxjs/operators';

const source: Observable<number[]> = from([[1,2],[3,4]]);

// OK
const test0: Observable<number[]> = source.pipe(take(1));

// OK  test1: Observable<number[]>
const test1 = source.pipe(take(1));

// OK
const test2: Observable<number> = source.pipe(concatAll());

// Bug?  Observable<{}> instead of Observable<number>
const test3 = source.pipe(concatAll());

// Bug?   pipe<any, number> 
const test4: Observable<number> = source.pipe(take(1), concatAll());


/* Bug? pipe<any, {}, {}>

Type 'Observable<{}>' is not assignable to type 'Observable<number>'. Type '{}' is not assignable to type 'number'.
*/
const test5: Observable<number> = source.pipe(take(1), concatAll(), take(1));


// OK typings seem to work with explicit types
const test6 = source.pipe<number[], number, number>(take(1), concatAll(), take(1));
const test7: Observable<number> = source.pipe<number[], number, number>(take(1), concatAll(), take(1));
```

**Additional information:**

All observables above at compile time raise this

```
node_modules/rxjs/internal/Observable.d.ts(71,59): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
node_modules/rxjs/internal/types.d.ts(34,84): error TS2304: Cannot find name 'Iterable'.
node_modules/rxjs/internal/types.d.ts(36,6): error TS2304: Cannot find name 'Symbol'.
```

**Comment by benlesh** [comment]
Seems to be an issue with the typings for `concatAll()`

**Comment by benlesh** [comment]
@krodyrobi This all appears to be working fine in TS 2.8 and 6.0.0-rc.0

Can't reproduce.

**Comment by krodyrobi** [comment]
@benlesh 
Thank you for looking into this.
I still get an error on the `test5` (from above, or `test` in the provided sample).
It goes away when I explicitly add hints on the pipe, this is happening even in `6.0.0-rc.0`.

[minimal-sample.zip](https://github.com/ReactiveX/rxjs/files/1877131/minimal-sample.zip)

```npm run tsc```

```
index.ts(26,69): error TS2345: Argument of type 'MonoTypeOperatorFunction<number>' is not assignable to parameter of type 'OperatorFunction<number[], {}>'.
  Types of parameters 'source' and 'source' are incompatible.
    Type 'Observable<number[]>' is not assignable to type 'Observable<number>'.
      Type 'number[]' is not assignable to type 'number'.
```

**Comment by alex-okrushko** [comment]
@krodyrobi are you using angular as well?

**Comment by krodyrobi** [comment]
In this sample I did not, haven't tried with the new Angular.

**Comment by alex-okrushko** [comment]
@krodyrobi I had the same error message when I'm using rxjs v6, angular 5.x and rxjs-compat (because angular 5.x needs it).
The issue was happening because I was using `async` pipe that was using the compat version of rxjs, yet I was providing v6 observable to it.
