### ISSUE TITLE
FromObservable.from requires mapFnOrScheduler parameter

### ISSUE THREAD

**Issue by pcroc** [ReactiveX/RxJS#1444]
I have this code which used to work with rxjs 5.0.0-beta0:  
```typescript
return Rx.Observable.from(this.basketChanges).skip(1);
```

But with beta2 this now gives an error: (138,12): error TS2346: Supplied parameters do not match any signature of call target.

Inspecting FromObservable.d.ts shows that the Observable.from has a second required parameter:  
```
static create<T>(ish: any, mapFnOrScheduler: Scheduler | ((x: any, y: number) => T) .... 
```

It looks like this should have been fixed by commit efa4dc3e6ce9cd7238a852cdb294d7f2c59caea1 but it appears not.

**Comment by kwonoj** [comment]
Would you able to try with master? it seems like fix was checked in after release of beta.2,

**Comment by pcroc** [comment]
Yes it is fixed when I build master. When is the next beta likely to be released?

**Comment by kwonoj** [comment]
It seems likely happen in couple of weeks. (exact date may vary). Let me close issue since it's fixed in master already.
